wandb_version: 1

epochs:
  desc: null
  value: 1000
classes:
  desc: null
  value: 3
base_c:
  desc: null
  value: 12
kernels:
  desc: null
  value:
  - 6
  - 12
  - 24
  - 48
norm_name:
  desc: null
  value: batch
batch_size:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0003
dataset:
  desc: null
  value: REFUGE
architecture:
  desc: null
  value: unet
seed:
  desc: null
  value: 670
transform:
  desc: null
  value: true
low_loss_path:
  desc: null
  value: /home/kebl6872/Desktop/new_data/REFUGE/test/promptunet_batch_lr_0.0003_bs_16_fs_12_[6_12_24_48]/Checkpoint/seed/670/lr_0.0003_bs_16_lowloss.pth
final_path:
  desc: null
  value: /home/kebl6872/Desktop/new_data/REFUGE/test/promptunet_batch_lr_0.0003_bs_16_fs_12_[6_12_24_48]/Checkpoint/seed/670/lr_0.0003_bs_16_final.pth
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702255000.522255
    t:
      1:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 55
      - 80
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
