wandb_version: 1

epochs:
  desc: null
  value: 75
disc_only:
  desc: null
  value: false
cup_only:
  desc: null
  value: true
classes:
  desc: null
  value: 2
base_c:
  desc: null
  value: 12
kernels:
  desc: null
  value:
  - 16
  - 32
  - 64
  - 128
norm_name:
  desc: null
  value: batch
batch_size:
  desc: null
  value: 15
learning_rate:
  desc: null
  value: 3.0e-05
dataset:
  desc: null
  value: REFUGE
architecture:
  desc: null
  value: unet
low_loss_path:
  desc: null
  value: /home/kebl6872/Desktop/new_data/REFUGE2/test/cup_only/1600_unet_batch_lr_3e-05_bs_15_fs_12_[16_32_64_128]/Checkpoint/lr_3e-05_bs_15_lowloss.pth
final_path:
  desc: null
  value: /home/kebl6872/Desktop/new_data/REFUGE2/test/cup_only/1600_unet_batch_lr_3e-05_bs_15_fs_12_[16_32_64_128]/Checkpoint/lr_3e-05_bs_15_final.pth
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699900393.994358
    t:
      1:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 55
      - 80
      3:
      - 1
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
